// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ski_pass.proto

#include "ski_pass.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace ski_pass {
namespace protos {
class SkiPassRunInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SkiPassRunInfo> _instance;
} _SkiPassRunInfo_default_instance_;
}  // namespace protos
}  // namespace ski_pass
static void InitDefaultsscc_info_SkiPassRunInfo_ski_5fpass_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ski_pass::protos::_SkiPassRunInfo_default_instance_;
    new (ptr) ::ski_pass::protos::SkiPassRunInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ski_pass::protos::SkiPassRunInfo::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SkiPassRunInfo_ski_5fpass_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SkiPassRunInfo_ski_5fpass_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ski_5fpass_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_ski_5fpass_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ski_5fpass_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ski_5fpass_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ski_pass::protos::SkiPassRunInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ski_pass::protos::SkiPassRunInfo, input_skp_name_),
  PROTOBUF_FIELD_OFFSET(::ski_pass::protos::SkiPassRunInfo, debug_log_),
  PROTOBUF_FIELD_OFFSET(::ski_pass::protos::SkiPassRunInfo, run_status_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ski_pass::protos::SkiPassRunInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ski_pass::protos::_SkiPassRunInfo_default_instance_),
};

const char descriptor_table_protodef_ski_5fpass_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016ski_pass.proto\022\017ski_pass.protos\"r\n\016Ski"
  "PassRunInfo\022\026\n\016input_skp_name\030\001 \001(\t\022\021\n\td"
  "ebug_log\030\002 \001(\t\0225\n\nrun_status\030\003 \001(\0162!.ski"
  "_pass.protos.SkiPassRunStatus*+\n\020SkiPass"
  "RunStatus\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001b\006prot"
  "o3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ski_5fpass_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_ski_5fpass_2eproto_sccs[1] = {
  &scc_info_SkiPassRunInfo_ski_5fpass_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ski_5fpass_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ski_5fpass_2eproto = {
  false, false, descriptor_table_protodef_ski_5fpass_2eproto, "ski_pass.proto", 202,
  &descriptor_table_ski_5fpass_2eproto_once, descriptor_table_ski_5fpass_2eproto_sccs, descriptor_table_ski_5fpass_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_ski_5fpass_2eproto::offsets,
  file_level_metadata_ski_5fpass_2eproto, 1, file_level_enum_descriptors_ski_5fpass_2eproto, file_level_service_descriptors_ski_5fpass_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ski_5fpass_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_ski_5fpass_2eproto)), true);
namespace ski_pass {
namespace protos {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SkiPassRunStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ski_5fpass_2eproto);
  return file_level_enum_descriptors_ski_5fpass_2eproto[0];
}
bool SkiPassRunStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void SkiPassRunInfo::InitAsDefaultInstance() {
}
class SkiPassRunInfo::_Internal {
 public:
};

SkiPassRunInfo::SkiPassRunInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ski_pass.protos.SkiPassRunInfo)
}
SkiPassRunInfo::SkiPassRunInfo(const SkiPassRunInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  input_skp_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_input_skp_name().empty()) {
    input_skp_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_input_skp_name(),
      GetArena());
  }
  debug_log_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_debug_log().empty()) {
    debug_log_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_debug_log(),
      GetArena());
  }
  run_status_ = from.run_status_;
  // @@protoc_insertion_point(copy_constructor:ski_pass.protos.SkiPassRunInfo)
}

void SkiPassRunInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SkiPassRunInfo_ski_5fpass_2eproto.base);
  input_skp_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  debug_log_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  run_status_ = 0;
}

SkiPassRunInfo::~SkiPassRunInfo() {
  // @@protoc_insertion_point(destructor:ski_pass.protos.SkiPassRunInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SkiPassRunInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  input_skp_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  debug_log_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SkiPassRunInfo::ArenaDtor(void* object) {
  SkiPassRunInfo* _this = reinterpret_cast< SkiPassRunInfo* >(object);
  (void)_this;
}
void SkiPassRunInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SkiPassRunInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SkiPassRunInfo& SkiPassRunInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SkiPassRunInfo_ski_5fpass_2eproto.base);
  return *internal_default_instance();
}


void SkiPassRunInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ski_pass.protos.SkiPassRunInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  input_skp_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  debug_log_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  run_status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SkiPassRunInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string input_skp_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_input_skp_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ski_pass.protos.SkiPassRunInfo.input_skp_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string debug_log = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_debug_log();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ski_pass.protos.SkiPassRunInfo.debug_log"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .ski_pass.protos.SkiPassRunStatus run_status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_run_status(static_cast<::ski_pass::protos::SkiPassRunStatus>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SkiPassRunInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ski_pass.protos.SkiPassRunInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string input_skp_name = 1;
  if (this->input_skp_name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_input_skp_name().data(), static_cast<int>(this->_internal_input_skp_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ski_pass.protos.SkiPassRunInfo.input_skp_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_input_skp_name(), target);
  }

  // string debug_log = 2;
  if (this->debug_log().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_debug_log().data(), static_cast<int>(this->_internal_debug_log().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ski_pass.protos.SkiPassRunInfo.debug_log");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_debug_log(), target);
  }

  // .ski_pass.protos.SkiPassRunStatus run_status = 3;
  if (this->run_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_run_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ski_pass.protos.SkiPassRunInfo)
  return target;
}

size_t SkiPassRunInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ski_pass.protos.SkiPassRunInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string input_skp_name = 1;
  if (this->input_skp_name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_input_skp_name());
  }

  // string debug_log = 2;
  if (this->debug_log().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_debug_log());
  }

  // .ski_pass.protos.SkiPassRunStatus run_status = 3;
  if (this->run_status() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_run_status());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SkiPassRunInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ski_pass.protos.SkiPassRunInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const SkiPassRunInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SkiPassRunInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ski_pass.protos.SkiPassRunInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ski_pass.protos.SkiPassRunInfo)
    MergeFrom(*source);
  }
}

void SkiPassRunInfo::MergeFrom(const SkiPassRunInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ski_pass.protos.SkiPassRunInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.input_skp_name().size() > 0) {
    _internal_set_input_skp_name(from._internal_input_skp_name());
  }
  if (from.debug_log().size() > 0) {
    _internal_set_debug_log(from._internal_debug_log());
  }
  if (from.run_status() != 0) {
    _internal_set_run_status(from._internal_run_status());
  }
}

void SkiPassRunInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ski_pass.protos.SkiPassRunInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SkiPassRunInfo::CopyFrom(const SkiPassRunInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ski_pass.protos.SkiPassRunInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SkiPassRunInfo::IsInitialized() const {
  return true;
}

void SkiPassRunInfo::InternalSwap(SkiPassRunInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  input_skp_name_.Swap(&other->input_skp_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  debug_log_.Swap(&other->debug_log_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(run_status_, other->run_status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SkiPassRunInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protos
}  // namespace ski_pass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ski_pass::protos::SkiPassRunInfo* Arena::CreateMaybeMessage< ::ski_pass::protos::SkiPassRunInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ski_pass::protos::SkiPassRunInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
